version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image:
      marcellwar/inventario-web ## crear usuario de docker hub -------------------- https://hub.docker.com/
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://inventario_tienda_nmtf_user:KALBPyBP8j9AYFaqTMhuWCrr3qnfQ9LG@dpg-csq312hu0jms73fmg2h0-a.oregon-postgres.render.com/inventario_tienda_nmtf
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inventario_tienda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
